#!/bin/bash
#SBATCH --job-name=intaRNA
#SBATCH --partition=workq  #workq is the default and unique queue, you do not need to specify.
#SBATCH --account dimarco.federico
#SBATCH --mem=15GB  # amout of RAM in MB required (and max ram available). Xor "--mem-per-cpu"
#SBATCH --time=INFINITE  ## OR #SBATCH --time=10:00 means 10 minutes OR --time=01:00:00 means 1 hour
#SBATCH --ntasks=1  # nubmer of required cores
#SBATCH --nodes=1  # not really useful for not mpi jobs
#SBATCH --mail-type=ALL ## BEGIN, END, FAIL or ALL
#SBATCH --mail-user=dimarco.federico@hsr.it
#SBATCH --error="/beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/slurm/out.err"
#SBATCH --output="/beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/slurm/out.out"


(source /opt/common/tools/ric.cosr/miniconda3/bin/activate;
conda activate /home/dimarco.federico/envs/srna;
miranda /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/query/q.fasta /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/target/ec2.fa -en -4 -out /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/Raw/miranda;
{ grep "Seq1,Seq2" /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/Raw/miranda | head -n 1 | sed 's/,/;/g'; grep ">>" /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/Raw/miranda | sed 's/\t/;/g'| sed 's/ /_/g'| sed 's/>//g'; } > /beegfs/scratch/ric.cirillo/dimarco.federico/srna/Spot_bench/Predictions/miranda.csv)
